adjust puma config

diff --git a/bin/puma b/bin/puma
--- a/bin/puma
+++ b/bin/puma
@@ -6,27 +6,101 @@
 # this file is here to facilitate running it.
 #
 
-if ARGV[0] == '--kill-existing'
-  ARGV.delete_at(0)
+# if ARGV[0] == '--kill-existing'
+#   ARGV.delete_at(0)
 
-  pids = `ps aux | grep puma | grep discourse | grep -v grep | awk '{print $2;}'`.strip
-    .split("\n")
-    .map(&:to_i)
-    .reject{|pid| pid == Process.pid}
+#   pids = `ps aux | grep puma | grep discourse | grep -v grep | awk '{print $2;}'`.strip
+#     .split("\n")
+#     .map(&:to_i)
+#     .reject{|pid| pid == Process.pid}
 
-  if pids.length > 0
-    STDERR.puts "Terminating old version of puma at pid #{pids[0]}"
-    `kill -9 #{pids[0]}`
-    sleep 1
-  end
+#   if pids.length > 0
+#     STDERR.puts "Terminating old version of puma at pid #{pids[0]}"
+#     `kill -9 #{pids[0]}`
+#     sleep 1
+#   end
 
-end
+# end
 
-require 'pathname'
-ENV['BUNDLE_GEMFILE'] ||= File.expand_path("../../Gemfile",
-  Pathname.new(__FILE__).realpath)
+# require 'pathname'
+# ENV['BUNDLE_GEMFILE'] ||= File.expand_path("../../Gemfile",
+#   Pathname.new(__FILE__).realpath)
 
-require 'rubygems'
-require 'bundler/setup'
+# require 'rubygems'
+# require 'bundler/setup'
 
-load Gem.bin_path('puma', 'puma')
+# load Gem.bin_path('puma', 'puma')
+
+
+
+
+#! /bin/sh
+
+PUMA_CONFIG_FILE=/data/www/hlbf/current/config/puma.rb
+PUMA_PID_FILE=/data/www/hlbf/shared/tmp/pids/puma.pid
+PUMA_SOCKET=/data/www/hlbf/shared/tmp/sockets/puma.sock
+
+# check if puma process is running
+puma_is_running() {
+  if [ -S $PUMA_SOCKET ] ; then
+    if [ -e $PUMA_PID_FILE ] ; then
+      if cat $PUMA_PID_FILE | xargs pgrep -P > /dev/null ; then
+        return 0
+      else
+        echo "No puma process found"
+      fi
+    else
+      echo "No puma pid file found"
+    fi
+  else
+    echo "No puma socket found"
+  fi
+
+  return 1
+}
+
+case "$1" in
+  start)
+    echo "Starting puma..."
+      rm -f $PUMA_SOCKET
+      if [ -e $PUMA_CONFIG_FILE ] ; then
+        bundle exec puma -C $PUMA_CONFIG_FILE
+      else
+        bundle exec puma
+      fi
+
+    echo "done"
+    ;;
+
+  stop)
+    echo "Stopping puma..."
+      kill -s SIGTERM `cat $PUMA_PID_FILE`
+      rm -f $PUMA_PID_FILE
+      rm -f $PUMA_SOCKET
+
+    echo "done"
+    ;;
+
+  restart)
+    if puma_is_running ; then
+      echo "Hot-restarting puma..."
+      kill -s SIGUSR2 `cat $PUMA_PID_FILE`
+
+      echo "Doublechecking the process restart..."
+      sleep 5
+      if puma_is_running ; then
+        echo "done"
+        exit 0
+      else
+        echo "Puma restart failed :/"
+      fi
+    fi
+
+    echo "Trying cold reboot"
+    bin/puma.sh start
+    ;;
+
+  *)
+    echo "Usage: script/puma.sh {start|stop|restart}" >&2
+    ;;
+esac
